//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class schedule
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Ingrese Nombre")]
        [Display(Name = "Nombre del Cliente")]
        public string ClientName { get; set; }
        [Required(ErrorMessage ="Ingrese Fecha")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> Date { get; set; }
        [Required(ErrorMessage ="Ingrese Hora")]
        [DataType(DataType.Time)]
        [Display(Name = "Hora")]
        public Nullable<System.TimeSpan> Hour { get; set; }
    }
}
