//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class service
    {
        public int ID { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage ="Ingrese Nombre")]
        public string Name { get; set; }
        [Display(Name = "Descripción")]
        [Required(ErrorMessage ="Ingrese Descripción")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Required(ErrorMessage ="Ingrese Precio")]
        [Display(Name = "Precio")]
        [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
        public decimal Price { get; set; }
    }
}
